# Generated by Django 5.2.7 on 2025-10-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='Date Posted'),
        ),
    ]
